### ISSUE TITLE
Provide better context for the Source field in Ranking Criteria

### ISSUE THREAD

**Issue by Emptiest** [Quaver/Quaver.Wiki#134]
Currently, the [ranking criteria page](https://wiki.quavergame.com/docs/Ranking/Criteria) has only the two following lines regarding the source field:

* The artist and title must be romanized. However, non-romanized characters are allowed to be used in source and tags.
* The artist, title and source must not repeat in tags. However, romanizing or translating the source in tags is encouraged, in case it’s relevant.

A common issue new mappers have is that they do not understand what the source field should actually have filled in with. [The literal definition of source would suggest a [youtube] link works too](https://discord.com/channels/354206121386573824/526869603515760659/834493661030514788). Experienced mappers, especially those coming from osu, know that the source field should contain the [Album, game, anime, show, ect](https://discord.com/channels/354206121386573824/526869603515760659/834492940621185054)

However, there is no such indication on ranking criteria, so this is an easy to follow, yet unwritten thing that people can miss.

Please add some language to the page so people can be aware of how to fill in the source field properly. It doesn't feel good to get rejected by criteria that was not properly defined in the first place.

**Comment by Zephyr3755** [comment]
🤔 based on your concerning, i think it should be related to client too. But i'll consider adding it to my PR

**Comment by Emptiest** [comment]
Thanks! I do think it might be useful to have something in-client to explain this, but I don't have any idea where it would go. I do think this information at least belongs on the wiki, however, and the ranking criteria is probably the best place to include it since ranking supervisors are going to correct submissions and tell users to fix the source field regardless.

**Comment by Emptiest** [comment]
Zephyr asked me to tag his PR #133
