### ISSUE TITLE
OAuth usage is unclear

### ISSUE THREAD

**Issue by koneko** [Quaver/Quaver.Wiki#174]
As the title says, I have no clue why I would use the OAuth implementation as it isn't used for anything (as far as I can see from the docs), the only thing I can think of is downloading mapsets, which I have no clue also how to download (seriously, let me download mapsets from the server instead of from the web via API). If this could be cleared up, I would really appreciate it.

**Comment by AiAe** [comment]
Its used if you want to integrate linking Quaver accounts for 3rd party sites, like tournaments and so on
